version: '3.8'

services:
  mariadb:
    extends:
      file: ./compose/compose.db.yml
      service: mariadb
    healthcheck:
      test: "exit 0"

  tracing:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 16686:16686
      - 14268:14268
      - 4318:4318

  auth-api:
    extends:
      file: ./compose/compose.published.yml
      service: auth-api
    depends_on:
      mariadb:
        condition: service_healthy

  user-api:
    extends:
      file: ./compose/compose.published.yml
      service: user-api
    depends_on:
      mariadb:
        condition: service_healthy

  hotel-api:
    extends:
      file: ./compose/compose.published.yml
      service: hotel-api
    depends_on:
      mariadb:
        condition: service_healthy

  reservation-api:
    extends:
      file: ./compose/compose.published.yml
      service: reservation-api
    depends_on:
      mariadb:
        condition: service_healthy

  front:
    extends:
      file: ./compose/compose.published.yml
      service: front

networks:
  default:
    external: true
    name: grpc-task-manager_default
