// @generated by protobuf-ts 2.9.0
// @generated from protobuf file "hotel/service.proto" (package "hotel", syntax proto3)
// tslint:disable
import { FindResponse } from "./hotel";
import { FindRequest } from "./hotel";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service hotel.HotelCRUDService
 */
export const HotelCRUDService = new ServiceType("hotel.HotelCRUDService", [
    { name: "Find", options: {}, I: FindRequest, O: FindResponse }
]);
